# Generated by Django 3.2.8 on 2021-11-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userrole_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not shared', 'Not Shared')], default='not shared', max_length=50),
        ),
    ]
