# Generated by Django 3.2.8 on 2021-11-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_details_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='profile_pic',
            field=models.TextField(blank=True),
        ),
    ]
