# Generated by Django 3.2.8 on 2021-11-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_details_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='profile_pic',
            field=models.TextField(blank=True, default='profilepicture/p1.jpeg'),
        ),
    ]
