# Generated by Django 3.2.8 on 2021-10-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceitemobject',
            name='prod_price',
            field=models.CharField(default='$0', max_length=5),
        ),
    ]
