# Generated by Django 3.2.8 on 2021-10-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_marketplaceitemobject_prod_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceitemobject',
            name='prod_comment',
            field=models.TextField(blank=True, default='New Comment'),
        ),
    ]
