# Generated by Django 3.2.8 on 2021-10-31 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_marketplaceitemobject_prod_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceitemobject',
            name='prod_comment',
        ),
    ]
