# Generated by Django 3.2.8 on 2021-11-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_marketplaceitemobject_prod_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitemobject',
            name='prod_comment',
            field=models.TextField(blank=True),
        ),
    ]
