# Generated by Django 3.2.8 on 2021-11-14 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0019_alter_marketplaceitemobject_prod_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitemobject',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
