# Generated by Django 3.2.8 on 2021-11-14 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0020_marketplaceitemobject_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceitemobject',
            name='user',
        ),
        migrations.AlterField(
            model_name='marketplaceitemobject',
            name='prod_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
