# Generated by Django 3.2.8 on 2021-11-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_auto_20211114_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplaceitemobject',
            old_name='prod_seller',
            new_name='user',
        ),
    ]
