# Generated by Django 3.2.8 on 2021-11-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_marketplaceitemobject_prod_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceitemobject',
            name='prod_seller',
        ),
    ]
