# Generated by Django 3.2.8 on 2021-11-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_remove_marketplaceitemobject_prod_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitemobject',
            name='prod_seller',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
