# Generated by Django 3.2.8 on 2021-11-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_createcomment_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcomment',
            name='role',
        ),
    ]
